user/routes.py
from flask import Blueprint, request, render_template

# from app import login_manager
from user.UserController import *
from user import LoginForm, RgisterForm


# 建立(註冊)路由的函式
UserRoutes = Blueprint('UserRoutes', __name__, template_folder="templates", static_folder="static")

print(UserRoutes.root_path)


# 按间距中的绿色按钮以运行脚本。
@UserRoutes.route('', methods=['GET'], endpoint='start')
@UserRoutes.route('/index', methods=['GET'], endpoint='sec')
def index():
    if "signal" in session:
        report = session["signal"]
        if type(report) is not dict:
            session.clear()
            return redirect(url_for('start'))
        if 'index' in request.path:  # endpoint='sec'
            session.clear()
            form = LoginForm() if report['login'] else RgisterForm()
            return render_template('index.html', login=report['login'], form=form, getinfo=report['getinfo'],
                                   message=report['message'])
        else:
            return render_template('index.html', login=True, form=LoginForm())
    return render_template('index.html', login=True, form=LoginForm())


# 註冊
@UserRoutes.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RgisterForm()
    print(form.validate_on_submit())
    if form.validate_on_submit():
        pw_hash = Users.hash_password(form.Password.data)
        return CreateUser(account=form.Account.data, email=form.Email.data,
                          password=pw_hash)
    else:
        return render_template('index.html', login=False, form=form)


# 電子郵件認證
@UserRoutes.route('/vaild/confirm/', methods=['POST'])
def Activate_account():
    data = request.values.to_dict()
    return CheckUser(data['token'], data['random'])


# 登入
@UserRoutes.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.find_by_Email(form.Email.data)
        from app import bcrypt, login_manager
        if user and user.match_password(form.Password.data, bcrypt=bcrypt):
            pass# login_manager()
        else:
            session["signal"] = {"login": True, "getinfo": True,
                                 "message": Message["Error_msg4"].format(form.Email.data)}
            return redirect(url_for('UserRoutes.sec'))
    else:
        return render_template('index.html', login=True, form=form)


# 登出
@UserRoutes.route('/logout', methods=['GET'])
def logout():  # 使用者註冊
    return "LogoutUser()"


# 讀取資訊
@UserRoutes.route('/info', methods=['GET'])
def info():
    return "InfoUser()"


# 編輯
@UserRoutes.route('/edit', methods=['GET'])
def edit():
    return "EditUser()"


# 刪除
@UserRoutes.route('/delete', methods=['GET'])
def delete():
    return "DeleteUser()"

templates/index.html
{% extends 'bootstrap/base.html' %}
{% block title %}This is the index page{% endblock %}

{% block head %}
  {% block style %}
  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
  <link rel="shortcut icon" href="#"/>
  <link href="{{url_for('static', filename='css/signin.css')}}" rel="stylesheet">
  <link href="{{url_for('static', filename='bootstrap5/css/bootstrap.min.css')}}" rel="stylesheet">
  <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sign-in/">
  {% endblock style %}

  {% block metas %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.88.1">
  {% endblock metas %}

{% endblock head %}


{% block body %}
  <body class="text-center">
{% block content %}
{% import "bootstrap/wtf.html" as wtf %}
  <main class="form-signin">
{% if login == False %}
    <form action="{{url_for('UserRoutes.signup')}}" method="post">
        {{form.csrf_token}}

      <a href="{{url_for('IndexRoutes.start')}}">
          <img class="mb-4" src="{{url_for('static', filename='imgs/logo.png')}}" alt="" width="300" height="auto">
      </a>

      <h1 class="h3 mb-3 fw-normal">Sign up</h1>

      <div class="form-floating">
          {{form.account(class="form-control", placeholder="username")}}
          {{form.account.label(class='form-label')}}
      </div>
{% else %}
    <form action="{{url_for('UserRoutes.login')}}" method="post">
        {{form.csrf_token}}

      <a href="{{url_for('IndexRoutes.start')}}">
          <img class="mb-4" src="{{url_for('static', filename='imgs/logo.png')}}" alt="" width="300" height="auto">
      </a>

      <h1 class="h3 mb-3 fw-normal">Sign in</h1>
{% endif %}
      <p></p>

      <div class="form-floating">
          {{form.email(class="form-control", placeholder="xxx@gmail.com")}}
          {{form.email.label(class='form-label')}}
      </div>

      <p></p>

      <div class="form-floating">
          {{form.password(class="form-control", placeholder="Password")}}
          {{form.password.label(class='form-label')}}
      </div>

      <p></p>

{% if login == False %}
      <div class="form-floating">
          {{form.confirm(class="form-control", placeholder="Repeat password")}}
          {{form.confirm.label(class='form-label')}}
      </div>

      <p></p>
{% endif %}

{% if login == True %}
          {{form.submit(class="w-100 btn btn-lg btn-primary")}}
    </form>

      <p></p>

    <form>
        <button class="w-100 btn btn-lg btn-secondary" type="submit" formaction="{{url_for('UserRoutes.signup')}}" formmethod="get">Sign up</button>
    </form>
    {% else %}
          {{form.submit(class="w-100 btn btn-lg btn-secondary")}}
    </form>

      <p></p>
    <form>
        <button class="w-100 btn btn-lg btn-primary" type="submit" formaction="{{url_for('IndexRoutes.start')}}" formmethod="get">Sign in</button>
    </form>
    {% endif %}

      <p></p>

{% if getinfo %}
    {% if "Success" in message %}
        <div class="alert alert-success" role="alert"><p>{{message}}</p></div>
    {% else %}
        <div class="alert alert-danger" role="alert"><p>{{message}}</p></div>
    {% endif %}
{% endif %}

      <p></p>

      <p class="mt-5 mb-3 text-muted" style="position: absolute; left: 50%;
      transform: translate(-50%, 0); bottom: 10px;">&copy; 2022</p>

  </main>
{% endblock content %}
  </body>
{% endblock body %}